---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-svc
  labels:
    db: mysql
spec:
  selector:
    db: mysql-db
  type: ClusterIP 
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql-db-port
      protocol: TCP  

  