---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-svc
  labels:
    db: mysql
spec:
  ports: 
    - port: 3306
      targetPort: 3306
      name: mysql-port
  selector:
    mysql-deploy
  type: ClusterIP  