apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: ci-cd
spec:
  minReadySeconds: 3
  replicas: 8
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 4
  template:
    metadata:
      name: app-jenkins
      labels:
        app: jenkins
        jdkversion: "jdk-11"
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
              name: jenkins-port
              protocol: TCP 
          livenessProbe:
            exec:
              command:
                - pwd 


      

                