---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 80
      name: nginx-app-port
      protocol: TCP 
  
