pipeline{
    agent{
        label 'node-1'
    }
    stages{
        stage('clone'){
            steps{
                sh """
                      docker image build -t gol:1.1 .
                      docker image tag gol:1.1 tarunkumarpendem/gol:1.1
                      docker image push tarunkumarpendem/gol:1.1
                    """   
            }
        }
    }
}