---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: word-press-application
  ports:
    - name: wordpress-webport
      port: 80